### ISSUE TITLE
multi @charset not removed

### ISSUE THREAD

**Issue by sascha-wojewsky-IPD** [yui/yuglify#15]
I'm using yuglify with --terminal.
Input:

``` css
@charset "UTF-8";
@media all {
  DIV.test1 {
    background: white;
  }
}
@charset "UTF-8";
@media all {
  DIV.test2 {
    background: red;
  }
}
@charset "UTF-8";
@media all {
  DIV.test3 {
    background: black;
  }
}
```

Output:

``` css
@charset "UTF-8";@media all{DIV.test1{background:white}}@charset "UTF-8";@media all{DIV.test2{background:red}}@media all{DIV.test3{background:black}}
```

Only one @charset was removed...
